### ISSUE TITLE
Request for Modified ARCSim

### ISSUE THREAD

**Issue by FishWoWater** [isantesteban/vto-dataset#1]
Thanks for your nice work!! 

Could you please provide the modified version of ARCSim?  The original version uses puppet model and I can't figure out how to drive it using MoCap sequences? 

By the way, do you have any code or resources on post-processing handling for mesh collision? I'd like to use it as a baseline. Thank you very much!!

**Comment by isantesteban** [comment]
Hi! Unfortunately I'm not allowed to share the modified version of ARCSim, but the code for the collision post-process can be found here: [https://github.com/isantesteban/vto-learning-based-animation/blob/main/src/postprocess.py](https://github.com/isantesteban/vto-learning-based-animation/blob/main/src/postprocess.py)

**Comment by FishWoWater** [comment]
Got it! Thanks for your prompt reply: )

**Comment by FishWoWater** [comment]
Hi! I have read your works and some other works on virtual try-on. I have one question:

Why don't you encode any mesh-relevant features directly? (e.g. mesh coords,  connectivity etc.) I think directly learning from `\beta`, `\theta`is much more difficult. But it seems that your work and TailorNet, DeepDrape, except garnet(++) follows this paradigm.  Is there any reason not to use the mesh as input? I guess the difficult to address irregular mesh can be one reason? (actually a recent work `meshgraphnets` addresses this problem)

Grateful if you could solve my concern. Thanks :)

**Comment by FishWoWater** [comment]
Besides, are you familiar with clo3d(https://www.clo3d.com/explore/whyclo)? I notice that clo3d is extremely fast in terms of cloth draping, which is somewhat counter-intuitive, since all the research claims that PBS is computationally intensive and very slow.

**Comment by FishWoWater** [comment]
Sorry to trouble you, but could you pls tell me how to ensure that garment's initial position is correct(collision-free or more) for arbitrary human poses in CMU mocap sequences?  I am also trying to make arcsim work on SMPL. Thanks :) @isantesteban

**Comment by isantesteban** [comment]
Hi! Sorry for the delay

> Why don't you encode any mesh-relevant features directly? (e.g. mesh coords, connectivity etc.) I think learning from \beta, \thetais much more difficult. But it seems that your works and TailorNet, DeepDrape, except garnet(++) follows this paradigm. Is there any reason not to use the mesh as input? I guess the difficultly to address irregular mesh can be one reason? (actually a recent work meshgraphnets addresses this problem). Another reason can be that the model is trained garment-wise(i.e. each type of garment uses a standalone model)?

The main advantage of mesh convolutions is being able to handle different garments with the same networks, we did some research about that in this paper: http://mslab.es/projects/FullyConvolutionalGraphVirtualTryOn/

Graph convolutional networks are harder to implement and slower at runtime, but it's certainly possible to learn garment deformations from mesh features. I don't have strong opinions about which approach is better, I think both are very interesting

> Besides, are you familiar with clo3d(https://www.clo3d.com/explore/whyclo)? I notice that clo3d is extremely fast in terms of cloth draping, which is somewhat counter-intuitive, since all the research claims that PBS is computationally intensive and very slow.

I think the challenge is making physics-based simulations that are both fast _and_ accurate. For example, in Arcsim we can generate animations quite fast if we lower the resolution of the t-shirt and reduce the precision of the solver, but the realism takes a significant hit. For virtual try-on the results need to be accurate, so in our research we compare with simulations that we have configured to prioritize accuracy, and those are computationally intensive and slow. I'm not familiar with what method clo3d uses to simulate garments, so I cannot comment about its accuracy.

> Sorry to trouble you, but could you pls tell me how to ensure that garment's initial position is correct(collision-free or more) for arbitrary human poses in CMU mocap sequences? I am also trying to make arcsim work on SMPL. Thanks

We describe our approach to initialize the simulations in Section 4.1 from this paper: [http://isantesteban.com/docs/EG2019/santesteban2019.pdf](http://isantesteban.com/docs/EG2019/santesteban2019.pdf).  The summary is that we initialize all simulations in t-pose (for which we have a collision-free configuration) and then we interpolate towards the target pose and body shape. 

Let me know if you have any issues implementing that. I'm currently going through some stressful months, but I'll do my best to find time to answer

**Comment by FishWoWater** [comment]
Thanks for your so patient and helpful comments! Actually I have learnt a lot from your works on virtual try-on :+1: 

I have gone through Section4.1 of your paper and now I will try to implement that 

Wish you can pull through @isantesteban

**Comment by FishWoWater** [comment]
![image](https://user-images.githubusercontent.com/37951601/164214186-a5880294-0a1e-48d3-a3cd-039bad7978f6.png)
![image](https://user-images.githubusercontent.com/37951601/164214311-d82e07ff-2ad4-4daa-8f67-c08bc0540ad5.png)

I managed to incorporate SMPL model and shape / pose interpolation, but there are some obvious artifacts for some frames. 

Do you have any ideas on this? I think a possible cause is the simluation speed, including interpolation speed. I set the time of one frame to 0.0167s and one frame consists of 10 steps.   I use 50 frames at the beginning for shape / pose interpolation.

**Comment by FishWoWater** [comment]
Thanks for you suggestions and quick reply!!!  

 Actually this happened during the simulation, but your experience on the initialization part will definitely help me a lot~

Yes, as you mention, I have tried to lower the time step it becomes better. I think the reason is the motion `kick` is very fast so some artifacts can appear during this period, and it will disappear when the motion slows down. 

Thank you again :+1:

**Comment by dancasas** [comment]
Hi @FishWoWater, please let us know if your modified ARCSim version to create garments for SMPL will be open sourced, we would be very happy to link it from our project website. Thanks!

**Comment by FishWoWater** [comment]
@dancasas 
Hi, dancasas! Glad to hear that! 

Yes, I just open-sourced it today.  You can find it here [https://github.com/FishWoWater/ARCSim-For-SMPL](https://github.com/FishWoWater/ARCSim-For-SMPL) =)

I am not a C++ expert, so I am afraid it's not that elegant in many places, but if more people can use it, I would have the chance to make it better.

**Comment by dancasas** [comment]
Great, thanks! And thanks again for your interest in our work.

**Comment by FishWoWater** [comment]
@dancasas Hi, dancasas!   

I have one more question:  it seems that your work (and actually almost all learning-based and many PBS methods) assumes the cloth to be a sheet. Is this a over-simplification? I think it leads to unreal garments in many cases.

Thanks
